### ISSUE TITLE
Liquidity problem with the original ROUTER/FACTORY

### ISSUE THREAD

**Issue by Trynight** [nguyenphu27/pancake-swap-exchange-testnet#16]
Hi!

As the title said, i've try setting the original router/factory address for testing the code, but it seems to still give the error of "no liquidity".

What is the problem? I've switched on mainnet (bsc) too..

**Comment by nguyenphu27** [comment]
hi, the router & factory addresses in my repositories are only applicable on the testnet. For the mainnet, you have to deploy a new one or use an existing like pcs or another dex.
Also if you want to try swapping your tokens, you need to add liquidity to your token first.

**Comment by Trynight** [comment]
> hi, the router & factory addresses in my repositories are only applicable on the testnet. For the mainnet, you have to deploy a new one or use an existing like pcs or another dex. Also if you want to try swapping your tokens, you need to add liquidity to your token first.

Thanks for the reply! Then, looking even better at the code, I was able to understand that the SDK had to be changed with the original one, however it works well on the mainnet and I integrated it into my dapp. Congratulations on extracting pcs swap.
