### ISSUE TITLE
How to add token in Swap?

### ISSUE THREAD

**Issue by MusabShakeel576** [nguyenphu27/pancake-swap-exchange-testnet#2]
There is only BNB in the Swap, how do I add other tokens like CAKE, DAI etc. to test the Swap in testnet.

**Comment by nguyenphu27** [comment]
You have to create your token on testnet first then using my interface to add liquidity for your token/BNB. 
After that you can do swap between token/BNB

**Comment by MusabShakeel576** [comment]
DAI, USDT, CAKE and few more are already in testnet, how do I add liquidity of these tokens into your interface through my MetaMask BSC testnet, I'm unable to search them?

![Screenshot_1](https://user-images.githubusercontent.com/46605319/126061473-16faf826-deaf-4e94-8934-9c44bd6fc996.png)

**Comment by nguyenphu27** [comment]
Seems like you are new to smart contract development? My interface just helps developer add/remove liquidity on testnet.
So please ignore the tokens list in search function, you can't use those tokens to add/remove or swap.
You have to deploy your new token, then using it to add/remove liquidity

**Comment by MusabShakeel576** [comment]
Oh OK, I'm trying to achieve something else, maybe pancakeswap-frontend repo is correct for it, thanks.
