### ISSUE TITLE
Testnet network only?

### ISSUE THREAD

**Issue by empiricustoken** [nguyenphu27/pancake-swap-exchange-testnet#3]
I was wondering if i can put mainnet or only works with net test.

**Comment by nguyenphu27** [comment]
Only work with testnet. For mainnet, you can use directly on Pancakeswap :v

**Comment by empiricustoken** [comment]
The problem is that pancake still doesn't have v2 support. Please contact me at telegram @H4llks, I would love to ask questions about the development.

**Comment by nguyenphu27** [comment]
I think you have to know that what differences between V1 and V2, they just update the smart contract and deployed to new contract address likes PancakeRouterV2.sol and PancakeFactoryV2.sol. 
My repo is already supported these changes and adapted to new UI V2. Still confusing what do you want =))

**Comment by PhatJay76** [comment]
I am attempting to get this code to work on mainnet using pancake router, factory and init hash, but it doesn't seem to work.   I am able to make this work just fine on testnet.
