### ISSUE TITLE
v1 deploy

### ISSUE THREAD

**Issue by LmingXie** [nguyenphu27/pancake-swap-exchange-testnet#4]
hello!
I had some problems deploying the V1 contract.Can you share the v1 deployment process,thanks !

**Comment by nguyenphu27** [comment]
The deployment process is the same V2, just using V1 contract instead. You can refer the process for how to deploy router and factory here: pancakeswap/pancake-swap-interface-v1#304 (comment).
But I would suggest you use the V2 since the V1 was deprecated.
