### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by yavci181** [nguyenphu27/pancake-swap-exchange-testnet#5]
I am getting an error like this. 

Failed to compile
src\connectors\index.ts
  Line 6:30:  Unable to resolve path to module '@binance-chain/bsc-connector'  import/no-unresolved

src\hooks\useAuth.ts
  Line 3:36:  Unable to resolve path to module '@binance-chain/bsc-connector'  import/no-unresolved

**Comment by nguyenphu27** [comment]
seems like you haven't installed dependencies completely
