### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by marquis-ogre** [nguyenphu27/pancake-swap-exchange-testnet#6]
Just cloned and compiled with out any changes but still failed with these errors. This worked pefectly 3 days back 

![image](https://user-images.githubusercontent.com/39271918/133324486-aca43d82-a070-4ead-8ca1-3976ef7be88f.png)

**Comment by diegoalejandrogomez** [comment]
same here

**Comment by nguyenphu27** [comment]
Oh, let me take a look..

**Comment by marquis-ogre** [comment]
Thanks for your concern, finally made it working with pancake-swap last commit and made some fixes, working perfectly.

**Comment by nguyenphu27** [comment]
Hi, The issue  is due to the eslint-config-pancake package. Just pushed the commit to fix this one. Please pull the latest commit.
It should work now.
